### ISSUE TITLE
Please consider fixing issues found by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [TA2k/ioBroker.mihome-cloud#6]
Adapter Checker (https://www.iobroker.dev/adapter-check) reports several issues for this adapter. Please consider fixing them.

In addition no release tags and no release are visible at guithub. Please consider using the iobroker release script environment.

[E120] Unknown type found in io-package.json
[E402] Types of adapter in latest repository and in io-package.json are different "iot-systems" !== "it-systems"
[E405] Icon must be in the following path: https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/
[E407] Meta URL (latest) must be equal to https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/io-package.json
[E422] Types of adapter in stable repository and in io-package.json are different "iot-systems" !== "it-systems"
[E426] Icon (stable) must be in the following path: https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/
[E428] Meta URL (stable) must be equal to https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/io-package.json
[E606] Current adapter version 0.0.5 not found in README.md
[E605] No actual year found in copyright. Please add "Copyright (c) 2023 TA2k <tombox2020@gmail.com>" at the end of README.md
[E701] No actual year found in LICENSE. Please add "Copyright (c) 2023 TA2k <tombox2020@gmail.com>" at the start of LICENSE

[W171] "common.title" is deprecated in io-package.json
[W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
[W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
[W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
[W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
[W515] Why you decided to disable i18n support?

**Comment by TA2k** [comment]
fixed fixable errors

**Comment by mcm1957** [comment]
Hi,
Could you please state which errors are "not fixable"? 
If the checker produces incorrect errors an issue should be opend there.

In addtion could you please explain why you do not use the releasescritp and/or use release tags within github. (Or do I oversee anything)?

Thanks for your work - you are really producing an etrem number of working (!) adapters.

I'm just interested why your repo difffers from "standard" setup in some ways. Please feel free to contact me per direct e-mail (mcm57@gmx.at) or at telegram developer if prefered.

**Comment by TA2k** [comment]
```
[E405] Icon must be in the following path: https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/
1
[E407] Meta URL (latest) must be equal to https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/io-package.json
2
[E426] Icon (stable) must be in the following path: https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/
3
[E428] Meta URL (stable) must be equal to https://raw.githubusercontent.com/TA2k/ioBroker.mihome-cloud/main/io-package.json
4
```
cannot see where the issue is
The release script is for me effort. Bad translation and complex placeholder to add release information in readme 
I also see no need to have for adapter releases or tags

I use the latest create adapter to create the adapter they are still missing uk as language and add common.title
