### ISSUE TITLE
Adapter uses Sentry but standard info is missing at Readme.md

### ISSUE THREAD

**Issue by mcm1957** [TA2k/ioBroker.mihome-cloud#8]
This adapter uses setntry but no Sentry infomation for users is visible at Readme.md. Users should be informed about data transfer and th epossibility to disable this feature.

Please add the suggested Sentry infomation listed at https://github.com/ioBroker/plugin-sentry#how-can-i-get-my-sentry-account-as-a-developer:

```**This adapter uses Sentry libraries to automatically report exceptions and code errors to the developers.** For more details and for information how to disable the error reporting see [Sentry-Plugin Documentation](https://github.com/ioBroker/plugin-sentry#plugin-sentry)! Sentry reporting is used starting with js-controller 3.0.```

**Comment by TA2k** [comment]
done
